Practical_Training_View/Controllers/ArticalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Practical_Training_View.Models;

namespace Practical_Training_View.Controllers
{
    public class ArticalsController : Controller
    {
        private Hospital_Services_GiudDBEntities db = new Hospital_Services_GiudDBEntities();

        // GET: Articals
        public ActionResult Index()
        {
            
            var articals = db.Articals.Include(a => a.Admin);
            return View(articals.ToList());
            
        }
       
        
        // GET: Articals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artical artical = db.Articals.Find(id);
            if (artical == null)
            {
                return HttpNotFound();
            }
            return View(artical);
        }

        // GET: Articals/Create
        public ActionResult Create()
        {
            ViewBag.Admin_ID = new SelectList(db.Admins, "Admin_ID", "Admin_Name");
            return View();
        }

        // POST: Articals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Artical_ID,Artical_title,Artical_Subtitle,Artical_Date,Artical_Image,Artical_Content,Admin_ID")] Artical artical)
        {
            if (ModelState.IsValid)
            {
                db.Articals.Add(artical);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Admin_ID = new SelectList(db.Admins, "Admin_ID", "Admin_Name", artical.Admin_ID);
            return View(artical);
        }

        // GET: Articals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artical artical = db.Articals.Find(id);
            if (artical == null)
            {
                return HttpNotFound();
            }
            ViewBag.Admin_ID = new SelectList(db.Admins, "Admin_ID", "Admin_Name", artical.Admin_ID);
            return View(artical);
        }

        // POST: Articals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Artical_ID,Artical_title,Artical_Subtitle,Artical_Date,Artical_Image,Artical_Content,Admin_ID")] Artical artical)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artical).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Admin_ID = new SelectList(db.Admins, "Admin_ID", "Admin_Name", artical.Admin_ID);
            return View(artical);
        }

        // GET: Articals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artical artical = db.Articals.Find(id);
            if (artical == null)
            {
                return HttpNotFound();
            }
            return View(artical);
        }

        // POST: Articals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Artical artical = db.Articals.Find(id);
            db.Articals.Remove(artical);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Practical_Training_View/Controllers/BloodNeedsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Practical_Training_View.Models;

namespace Practical_Training_View.Controllers
{
    public class BloodNeedsController : Controller
    {
        private Hospital_Services_GiudDBEntities db = new Hospital_Services_GiudDBEntities();

        // GET: BloodNeeds
        public ActionResult Index()
        {
            var bloodNeeds = db.BloodNeeds.Include(b => b.Blood);
            return View(bloodNeeds.ToList());
        }

        // GET: BloodNeeds/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BloodNeed bloodNeed = db.BloodNeeds.Find(id);
            if (bloodNeed == null)
            {
                return HttpNotFound();
            }
            return View(bloodNeed);
        }

        // GET: BloodNeeds/Create
        public ActionResult Create()
        {
            ViewBag.Blood_ID = new SelectList(db.Bloods, "Blood_ID", "Blood1");
            return View();
        }

        // POST: BloodNeeds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,IsNeeded,Blood_ID")] BloodNeed bloodNeed)
        {
            if (ModelState.IsValid)
            {
                db.BloodNeeds.Add(bloodNeed);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Blood_ID = new SelectList(db.Bloods, "Blood_ID", "Blood1", bloodNeed.Blood_ID);
            return View(bloodNeed);
        }

        // GET: BloodNeeds/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BloodNeed bloodNeed = db.BloodNeeds.Find(id);
            if (bloodNeed == null)
            {
                return HttpNotFound();
            }
            ViewBag.Blood_ID = new SelectList(db.Bloods, "Blood_ID", "Blood1", bloodNeed.Blood_ID);
            return View(bloodNeed);
        }

        // POST: BloodNeeds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,IsNeeded,Blood_ID")] BloodNeed bloodNeed)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bloodNeed).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Blood_ID = new SelectList(db.Bloods, "Blood_ID", "Blood1", bloodNeed.Blood_ID);
            return View(bloodNeed);
        }

        // GET: BloodNeeds/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BloodNeed bloodNeed = db.BloodNeeds.Find(id);
            if (bloodNeed == null)
            {
                return HttpNotFound();
            }
            return View(bloodNeed);
        }

        // POST: BloodNeeds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BloodNeed bloodNeed = db.BloodNeeds.Find(id);
            db.BloodNeeds.Remove(bloodNeed);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Practical_Training_View/Controllers/Care_UnitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Practical_Training_View.Models;

namespace Practical_Training_View.Controllers
{
    public class Care_UnitsController : Controller
    {
        private Hospital_Services_GiudDBEntities db = new Hospital_Services_GiudDBEntities();

        // GET: Care_Units
        public ActionResult Index()
        {
            var care_Units = db.Care_Units.Include(c => c.Admin);
            return View(care_Units.ToList());
        }

        // GET: Care_Units/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Care_Units care_Units = db.Care_Units.Find(id);
            if (care_Units == null)
            {
                return HttpNotFound();
            }
            return View(care_Units);
        }

        // GET: Care_Units/Create
        public ActionResult Create()
        {
            ViewBag.Admin_ID = new SelectList(db.Admins, "Admin_ID", "Admin_Name");
            return View();
        }

        // POST: Care_Units/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Care_ID,Care_Name,Care_NumberOfemptybed,Care_NumberOfbed,Care_Info,Care_Description,Care_Numberofemployees,Admin_ID")] Care_Units care_Units)
        {
            if (ModelState.IsValid)
            {
                db.Care_Units.Add(care_Units);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Admin_ID = new SelectList(db.Admins, "Admin_ID", "Admin_Name", care_Units.Admin_ID);
            return View(care_Units);
        }

        // GET: Care_Units/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Care_Units care_Units = db.Care_Units.Find(id);
            if (care_Units == null)
            {
                return HttpNotFound();
            }
            ViewBag.Admin_ID = new SelectList(db.Admins, "Admin_ID", "Admin_Name", care_Units.Admin_ID);
            return View(care_Units);
        }

        // POST: Care_Units/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Care_ID,Care_Name,Care_NumberOfemptybed,Care_NumberOfbed,Care_Info,Care_Description,Care_Numberofemployees,Admin_ID")] Care_Units care_Units)
        {
            if (ModelState.IsValid)
            {
                db.Entry(care_Units).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Admin_ID = new SelectList(db.Admins, "Admin_ID", "Admin_Name", care_Units.Admin_ID);
            return View(care_Units);
        }

        // GET: Care_Units/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Care_Units care_Units = db.Care_Units.Find(id);
            if (care_Units == null)
            {
                return HttpNotFound();
            }
            return View(care_Units);
        }

        // POST: Care_Units/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Care_Units care_Units = db.Care_Units.Find(id);
            db.Care_Units.Remove(care_Units);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Practical_Training_View/Controllers/NewssesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Practical_Training_View.Models;

namespace Practical_Training_View.Controllers
{
    public class NewssesController : Controller
    {
        private Hospital_Services_GiudDBEntities db = new Hospital_Services_GiudDBEntities();

        // GET: Newsses
        public ActionResult Index()
        {
            var newsses = db.Newsses.Include(n => n.Admin);
            return View(newsses.ToList());
        }

        // GET: Newsses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Newss newss = db.Newsses.Find(id);
            if (newss == null)
            {
                return HttpNotFound();
            }
            return View(newss);
        }

        // GET: Newsses/Create
        public ActionResult Create()
        {
            ViewBag.Admin_ID = new SelectList(db.Admins, "Admin_ID", "Admin_Name");
            return View();
        }

        // POST: Newsses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Newss newss,HttpPostedFileBase ImgUpload)
        {
            if (ModelState.IsValid)
            {
                string fileName = ImgUpload.FileName;
                //string fileName =  ""+DateTime.Now.Year+DateTime.Now.Day+DateTime.Now.Month + ".jpg";
                ImgUpload.SaveAs(Server.MapPath("~/ImgUpload/") + fileName);
                newss.News_Image = fileName;
                db.Newsses.Add(newss);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Admin_ID = new SelectList(db.Admins, "Admin_ID", "Admin_Name", newss.Admin_ID);
            return View(newss);
        }

        // GET: Newsses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Newss newss = db.Newsses.Find(id);
            if (newss == null)
            {
                return HttpNotFound();
            }
            ViewBag.Admin_ID = new SelectList(db.Admins, "Admin_ID", "Admin_Name", newss.Admin_ID);
            return View(newss);
        }

        // POST: Newsses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "News_ID,News_Content,News_Image,News_Date,Admin_ID")] Newss newss)
        {
            if (ModelState.IsValid)
            {
                db.Entry(newss).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Admin_ID = new SelectList(db.Admins, "Admin_ID", "Admin_Name", newss.Admin_ID);
            return View(newss);
        }

        // GET: Newsses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Newss newss = db.Newsses.Find(id);
            if (newss == null)
            {
                return HttpNotFound();
            }
            return View(newss);
        }

        // POST: Newsses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Newss newss = db.Newsses.Find(id);
            db.Newsses.Remove(newss);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Practical_Training_View/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="ar">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Health Service </title>
    <link rel="shortcut icon" href="~/assets/images/fav.png" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="~/assets/images/fav.jpg">
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/all.min.css">
    <link rel="stylesheet" href="~/assets/css/animate.css">
    <link rel="stylesheet" href="~/assets/plugins/slider/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/plugins/slider/css/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/css/StyleSheet1.css" />
    <link rel="stylesheet" href="~/scss/bootstrap/scss/vendor/_rfs.scss" />
    <link rel="stylesheet" href="~/scss/theme/_responsive.scss" />
    <link rel="stylesheet" href="~/scss/theme-1.scss" />
    <link rel="stylesheet" href="~/scss/theme-2.scss" />
    <link rel="stylesheet" href="~/scss/theme-3.scss" />
    <link rel="stylesheet" href="~/scss/theme-4.scss" />
    <link rel="stylesheet" href="~/scss/theme-5.scss" />
    <link rel="stylesheet" href="~/scss/theme-6.scss" />
    <link rel="stylesheet" href="~/scss/theme-7.scss" />
    <link rel="stylesheet" href="~/scss/theme-8.scss" />
    <link rel="stylesheet" href="~/css/responsive.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" />




    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <body>
        <header class="container-fluid">
            <div class="container">
                <div class="row top-row">
                    <div class="col-md-4 logo">

                        <img src="~/assets/images/logo.jpg" style="width:100px ; height:100px ;margin-left:-150px; margin-top: -10px;" alt="">
                        <h5 style="margin-left: -50px ; margin-top: -50px ;">مستشفى بني سويف الجامعي</h5>
                        <a data-toggle="collapse" data-target="#menu-jk" href="#menu-jk"><i class="fas d-block d-md-none small-menu fa-bars"></i></a>
                    </div>
                    <div class="col-md-8 navse">
                        <div class="row">
                            <div class="col-lg-4 d-none d-lg-block cinfo">
                                <div class="cdetl">
                                    <div class="icon">
                                        <i class="fas fa-map-marker-alt"></i>
                                    </div>
                                    <div class="detail">
                                        <b>الموقع</b>
                                        <p>شارع محمد حسن, الشاملة </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-6 d-none d-md-block cinfo">
                                <div class="cdetl">
                                    <div class="icon">
                                        <i class="far fa-envelope"></i>
                                    </div>
                                    <div class="detail">
                                        <b>البريد الإلكترونى</b>
                                        <p>BNShospital@support.com</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-6 d-none d-md-block cinfo">
                                <div class="cdetl">
                                    <div class="icon">
                                        <i class="fas fa-phone-alt"></i>
                                    </div>
                                    <div class="detail">
                                        <b>اتصل بنا </b>
                                        <p>+11 7200 20 40 30</p>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div id="menu-jk" class="nav-sectionmk  row">
                    <ul>
                        <li><a href='@Url.Action("Index","BloodNeeds")'>الصفحة الرئيسية</a></li>
                        <li><a href='@Url.Action("Index","Newsses")'>اخر الأخبار</a></li>
                        <li><a href='@Url.Action("Index","Articals")'>معلومات تهمك </a></li>
                        <li><a href='@Url.Action("Index","Care_Units")'>الرعايات</a></li>
                        <li><a href='@Url.Action("Index","Departments")'>الاقسام </a></li>


                    </ul>
                </div>
            </div>
        </header>
        @RenderBody()
        <footer class="footer">
            <div class="container">
                <div class="row">

                    <div class="col-md-4 col-sm-12">
                        <h2>ذات صلة</h2>
                        <ul class="list-unstyled link-list">
                            <li><a ui-sref="about" href="#/about">تواصل معنا</a><i class="fa fa-angle-right"></i></li>
                            <li><a ui-sref="portfolio" href="#/portfolio">الرعايات</a><i class="fa fa-angle-right"></i></li>
                            <li><a ui-sref="products" href="#/products">الاقسام الداخلية</a><i class="fa fa-angle-right"></i></li>
                            <li><a ui-sref="gallery" href='@Url.Action("Index","Newsses")'>اخر الاخبار</a><i class="fa fa-angle-right"></i></li>

                        </ul>
                    </div>
                    <div class="col-md-4 col-sm-12 map-img">
                        <h2>تواصل معنا</h2>
                        <address class="md-margin-bottom-40">
                            شارع محمد حسن  <br>
                            الشاملة <br>
                            بني سويف <br>
                            Phone: +44 9159669599 <br>
                            Email: <a href="mailto:info@anybiz.com" class="">BNShospital@support.com</a><br>
                            Web: <a href="smart-eye.html" class="">www.BNShospital.in</a>
                        </address>

                    </div>
                </div>
            </div>


        </footer>
        <div class="copy">
            <div class="container">
                <a href="https://www.smarteyeapps.com/">2015 &copy; All Rights Reserved | Designed and Developed by A,H&M</a>

                <span>
                    <a><i class="fab fa-github"></i></a>
                    <a><i class="fab fa-google-plus-g"></i></a>
                    <a><i class="fab fa-pinterest-p"></i></a>
                    <a><i class="fab fa-twitter"></i></a>
                    <a><i class="fab fa-facebook-f"></i></a>
                </span>
            </div>

        </div>

    </body>



    <script src="~/assets/js/jquery-3.2.1.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/plugins/scroll-fixed/jquery-scrolltofixed-min.js"></script>
    <script src="~/assets/plugins/slider/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/script.js"></script>

</html>